<?php

namespace bamboo\domain\entities;

use bamboo\core\base\CObjectCollection;
use bamboo\core\db\pandaorm\entities\AEntity;


/**
 * Class CProductSheetActual
 * @package bamboo\app\domain\entities
 *
 * @author Bambooshoot Team <emanuele@bambooshoot.agency>
 *
 * @copyright (c) Bambooshoot snc - All rights reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 *
 * @date $date
 * @since 1.0
 *
 * @property CProductSheetModelPrototypeMaterial $productSheetModelPrototypeMaterial
 * @property CProductSheetModelPrototypeCategoryGroup $productSheetModelPrototypeCategoryGroup
 * @property CProductSheetModelPrototypeGender $productSheetModelPrototypeGender
 * @property CObjectCollection $productSheetModelActual
 * @property CProductSheetModelPrototypeSupport $productSheetModelPrototypeSupport
 *
 */
class CProductSheetModelPrototype extends AEntity
{
    protected $entityTable = 'ProductSheetModelPrototype';
    protected $primaryKeys = ['id'];

    public function update()
    {
        $this->updateDate = null;
        return parent::update(); // TODO: Change the autogenerated stub
    }
}